#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, find a compliant shell and define the shell variable
#       SH accordingly.
#
#   (2) You need the command `getopts` (POSIX 2008 feature). If this does not
#       exist, get a compliant shell or operating system.
#
#   Important for patching:
#
#   (1) This script is generated from the template file
#       `application/templates/unixStartScript.txt` in the Gradle project.
#       You can find a readable form of the template in the Gradle documentation
#       at https://docs.gradle.org/current/userguide/executable_jar.html
#
#   (2) The presence of the variable PROGNAME in this script is relied upon
#       by the Gradle daemon client.
#
#   (3) The two-character variable names in this script are relied upon
#       by the Gradle daemon client.
#
#   (4) Changes to this script in the areas marked with # [patch area begins]
#       and # [patch area ends] are preserved by the Gradle build, and will be
#       updated automatically when running `gradle wrapper`.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25031)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo >&2 "$*"
}

die () {
    echo >&2 "$*"
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result of `ulimit -n`
        # is checked to see if we have infinite file descriptors.
        MAX_FD=$( ulimit -n )
        if [ $? -eq 0 ] && [ "$MAX_FD" != unlimited ] ; then
            # Use the smaller of the current limit and 65536 for the new limit.
            case $MAX_FD in #(
              '' | [0-9] | [1-2][0-9][0-9][0-9][0-9]|[3-5][0-9][0-9][0-9][0-9]|6[0-4][0-9][0-9][0-9]|65[0-4][0-9][0-9]|655[0-2][0-9]|6553[0-6])
                if [ "$MAX_FD" -gt 65536 ] ; then
                    MAX_FD=65536
                fi
                ulimit -n "$MAX_FD"
              ;;
            esac
        fi
      ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS
#   * -cp "$CLASSPATH"
#   * DEFAULT_JVM_OPTS goes at the end because it may have --module-path etc. that must override other options
#   * jvmOptsFile content (at beginning)

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: This is a really slow way to loop through the args. We might want
        # to use a different approach in the future.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg onto the end
    done
fi

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, DEFAULT_JVM_OPTS goes at the end because it may have --module-path etc. that must override other options
#   * -D...appname settings
#   * CLASSPATH
#   * Main classname
#   * args from the command line
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Make use of the jvm config file if it exists.
# It's located in the exact same directory as this script (i.e. the project root)
jvmOptsFile="$APP_HOME/gradle.jvmargs"
if [ -f "$jvmOptsFile" ]; then
    # shellcheck disable=SC2129
    while read -r line; do
        # Remove leading and trailing whitespace
        line=$( echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' )
        # Skip empty lines or comments
        if [ -n "$line" ] && [ "$( echo "$line" | sed -e 's/^\([#].*\)\?$/X/' )" = "X" ]; then
            continue
        fi
        # Split the line into an array of arguments and append to the current argument list
        set -- "$@" $( eval echo "$line" )
    done < "$jvmOptsFile"
fi

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "ERROR: xargs is not available."
fi

# Use "xargs" to parse quoted args into separate arguments for the java command
printf '%s' "$*" | xargs -n 1 sh -c '"$JAVACMD" "$@"' sh